### ISSUE TITLE
Request for Block Design

### ISSUE THREAD

**Issue by Justin62628** [titimar16/Pynq-Z2-Audio-Video-Pipelines#2]
I found that it's quite impossible to build the project using the `.tcl` file provided (due to many fixed absolute paths lmao)
It'll be of great help if you provide a block design in `README.md` I guess, a screenshot will do!
Thanks in advance!

**Comment by tmaringer** [comment]
Hello @Justin62628 !

It's an old school project, I don't have this project set up on my computer nor the time to play with it for now. You can change these paths to absolute ones (all the files are provided in the _src_ folder). It should do the job.

You can also check this project: https://github.com/tmaringer/FPGA-Audio-Project. It's the same without the video part and there's a block in the `README.md` file

**Comment by Justin62628** [comment]
Got that, thanks!
